### Hekateros hekateros_control/ProductInfo message

# hardware versions
string  version_string    # hardware version string
int64   maj               # hardware major version
int64   min               # hardware minor version
int64   rev               # hardware revision

# product ids and description
string  product_name      # product name
uint32  product_id        # product unique id
string  desc              # product description

# environment
string  hostname          # hostname of Hekateros
