### Hekateros hekateros_control/Calibrate action

# Goal/Result/Feedback

uint8         force_recalib   # do [not] force recalibration of all joints
---  
HekOpState    op              # arm calibration state
                              #   UNCALIBRATED, CALIBRATING, CALIBRATED
---
string[]      name            # joint name
HekOpState[]  op              # joint operation state:
                              #   UNCALIBRATED, CALIBRATING, CALIBRATED
