#! /usr/bin/env python
## 
## Calibrate the Hekateros arm via an action server request
##

import roslib; roslib.load_manifest('hekateros_control')
import rospy

from hekateros_control.calibrate_ac import *

def feedback_h(fb):
    print "Calibration Feedback: " + fb

if __name__ == '__main__':
    calib_client = calibrate_ac(timeout=2)
    calib_client.request_calib(feedback_h)

    print calib_action.get_action_state()

